version: '3'
services:
  broker: 
    build: .
    ports:
      - 3000:3000
    restart: on-failure
    depends_on: 
        - rabbit
        - crossbar-server
    environment: 
      RABBIT_URL: amqp://rabbit:5672
      WS_URL: ws://crossbar:9000/ws
      WS_REALM: realm1

  test: 
    build: .
    command: npm run test
    depends_on: 
      - rabbit
      - crossbar-server
      - broker-dev
    network_mode: host
    environment: 
      RABBIT_URL: amqp://0.0.0.0:5672
      WS_URL: ws://crossbar:9000/ws
      WS_REALM: realm1

  broker-dev: 
    image: node
    command:
      - node
      - /broker/bin/broker.js
      - -d
    volumes:
      - .:/broker
    ports:
      - 3000:3000
    restart: on-failure
    depends_on: 
        - rabbit
        - crossbar-server
    environment: 
      RABBIT_URL: amqp://rabbit:5672
      WS_URL: ws://crossbar:9000/ws
      WS_REALM: realm1

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 9001:15672
      - 5672:5672
    restart: on-failure

  # Creates a crossbar router 
  crossbar:
    image: crossbario/crossbar
    volumes: 
      - .:/node
    user: '0'
    ports:
      - 9000:9000 

  # Creates a crossbar wamp server 
  crossbar-server:
    image: node
    environment: 
      CBURL: ws://crossbar:9000/ws
      CBREALM: realm1
    volumes: 
        - .:/app
    command: 
      - node 
      - /app/tests/ws.js
    restart: on-failure
    depends_on: 
      - crossbar